runtime: python39  # Cambia según la versión que estés usando

entrypoint: gunicorn -b 127.0.0.1:8000 app:app  # Reemplaza "app" con el nombre de tu archivo principal

handlers:
- url: /.*
  script: auto
